
export const RECEIVE_ALL_CATEGORIES = "RECEIVE_ALL_CATEGORIES"
export const RECEIVE_ALL_POSTS = "RECEIVE_ALL_POSTS"
export const RECEIVE_ALL_COMMENTS = "RECEIVE_ALL_COMMENTS"

export const UPVOTE_POST = "UPVOTE_POST"
export const DOWNVOTE_POST = "DOWNVOTE_POST"

export const DELETE_POST = "DELETE_POST"
export const CREATE_POST = "CREATE_POST"
export const EDIT_POST = "EDIT_POST"

export const UPDATE_POST_REDIRECT = "UPDATE_POST_REDIRECT"

export const UPVOTE_COMMENT = "UPVOTE_COMMENT"
export const DOWNVOTE_COMMENT = "DOWNVOTE_COMMENT"

export const DELETE_COMMENT = "DELETE_COMMENT"
export const CREATE_COMMENT = "CREATE_COMMENT"
export const EDIT_COMMENT = "EDIT_COMMENT"

